export type BountyZone = {
  id: string;
  name: string;
  coordinates: [number, number];
  rewardMinor: number;
  reason: "unexplored" | "stale" | "buyer-requested" | "missing-modality";
  evidence: string;
  band: "standard" | "priority" | "urgent";
  safeForDemo: boolean;
  routeIndex: number;
};

export const zones: BountyZone[] = [
  {
    id: "zone-south-access",
    name: "South access route",
    coordinates: [-0.01795, 51.5389],
    rewardMinor: 920,
    reason: "buyer-requested",
    evidence:
      "Forward camera frames, route position, sound level and one accessibility note",
    band: "urgent",
    safeForDemo: true,
    routeIndex: 2,
  },
  {
    id: "zone-river-gate",
    name: "River gate approach",
    coordinates: [-0.01485, 51.5404],
    rewardMinor: 610,
    reason: "missing-modality",
    evidence: "Camera frames plus ambient volume level; no continuous audio",
    band: "priority",
    safeForDemo: true,
    routeIndex: 5,
  },
  {
    id: "zone-north-loop",
    name: "North loop signage",
    coordinates: [-0.0168, 51.5421],
    rewardMinor: 380,
    reason: "stale",
    evidence: "Signage and obstruction scan with GPS accuracy",
    band: "standard",
    safeForDemo: true,
    routeIndex: 7,
  },
  {
    id: "zone-service-yard",
    name: "Restricted service yard",
    coordinates: [-0.0201, 51.5414],
    rewardMinor: 1240,
    reason: "unexplored",
    evidence: "Not routable",
    band: "urgent",
    safeForDemo: false,
    routeIndex: 9,
  },
  {
    id: "zone-camden-high",
    name: "Camden access corridor",
    coordinates: [-0.1426, 51.5416],
    rewardMinor: 780,
    reason: "buyer-requested",
    evidence: "Step-free route and signage scan",
    band: "priority",
    safeForDemo: true,
    routeIndex: 11,
  },
  {
    id: "zone-kings-cross",
    name: "King's Cross crossings",
    coordinates: [-0.1233, 51.5308],
    rewardMinor: 540,
    reason: "stale",
    evidence: "Crossing condition and obstruction scan",
    band: "standard",
    safeForDemo: true,
    routeIndex: 12,
  },
  {
    id: "zone-westminster",
    name: "Westminster footway",
    coordinates: [-0.1276, 51.501],
    rewardMinor: 920,
    reason: "missing-modality",
    evidence: "Access, crowding and surface report",
    band: "urgent",
    safeForDemo: true,
    routeIndex: 13,
  },
  {
    id: "zone-southbank",
    name: "South Bank riverside",
    coordinates: [-0.1167, 51.5055],
    rewardMinor: 680,
    reason: "unexplored",
    evidence: "Riverside route and ambient conditions",
    band: "priority",
    safeForDemo: true,
    routeIndex: 14,
  },
  {
    id: "zone-shoreditch",
    name: "Shoreditch high street",
    coordinates: [-0.0799, 51.5257],
    rewardMinor: 460,
    reason: "stale",
    evidence: "Street works and pedestrian flow",
    band: "standard",
    safeForDemo: true,
    routeIndex: 15,
  },
  {
    id: "zone-greenwich",
    name: "Greenwich approach",
    coordinates: [0.0016, 51.4826],
    rewardMinor: 720,
    reason: "buyer-requested",
    evidence: "Hill approach and step-free alternatives",
    band: "priority",
    safeForDemo: true,
    routeIndex: 16,
  },
  {
    id: "zone-hammersmith",
    name: "Hammersmith interchange",
    coordinates: [-0.2248, 51.492],
    rewardMinor: 840,
    reason: "missing-modality",
    evidence: "Interchange access and signage",
    band: "urgent",
    safeForDemo: true,
    routeIndex: 17,
  },
  {
    id: "zone-richmond",
    name: "Richmond riverside",
    coordinates: [-0.3037, 51.4613],
    rewardMinor: 590,
    reason: "unexplored",
    evidence: "Riverside surface and obstruction scan",
    band: "standard",
    safeForDemo: true,
    routeIndex: 18,
  },
  {
    id: "zone-stratford",
    name: "Stratford Olympic loop",
    coordinates: [-0.0087, 51.5448],
    rewardMinor: 760,
    reason: "buyer-requested",
    evidence: "Station access, crowd flow and Olympic Park wayfinding",
    band: "priority",
    safeForDemo: true,
    routeIndex: 19,
  },
  {
    id: "zone-canary-wharf",
    name: "Canary Wharf dock edge",
    coordinates: [-0.0198, 51.5054],
    rewardMinor: 640,
    reason: "stale",
    evidence: "Dock crossing, lifts and temporary route closures",
    band: "priority",
    safeForDemo: true,
    routeIndex: 20,
  },
  {
    id: "zone-brixton",
    name: "Brixton market route",
    coordinates: [-0.114, 51.4627],
    rewardMinor: 530,
    reason: "missing-modality",
    evidence: "Market access, crowd flow and ambient volume",
    band: "standard",
    safeForDemo: true,
    routeIndex: 21,
  },
  {
    id: "zone-hackney",
    name: "Hackney Central corridor",
    coordinates: [-0.0556, 51.5471],
    rewardMinor: 690,
    reason: "unexplored",
    evidence: "Crossings, cycle-lane conflicts and station access",
    band: "priority",
    safeForDemo: true,
    routeIndex: 22,
  },
  {
    id: "zone-wembley",
    name: "Wembley event approach",
    coordinates: [-0.2795, 51.556],
    rewardMinor: 980,
    reason: "buyer-requested",
    evidence: "Crowd routing, barriers and step-free approach",
    band: "urgent",
    safeForDemo: true,
    routeIndex: 23,
  },
  {
    id: "zone-croydon",
    name: "Croydon tram interchange",
    coordinates: [-0.0986, 51.3752],
    rewardMinor: 710,
    reason: "stale",
    evidence: "Tram crossing, lifts and pavement conditions",
    band: "priority",
    safeForDemo: true,
    routeIndex: 24,
  },
  {
    id: "zone-woolwich",
    name: "Woolwich Elizabeth line",
    coordinates: [0.0692, 51.4915],
    rewardMinor: 820,
    reason: "missing-modality",
    evidence: "Station approach, signage and construction edge",
    band: "urgent",
    safeForDemo: true,
    routeIndex: 25,
  },
  {
    id: "zone-walthamstow",
    name: "Walthamstow market mile",
    coordinates: [-0.0199, 51.5832],
    rewardMinor: 570,
    reason: "unexplored",
    evidence: "Market congestion, kerb access and obstructions",
    band: "standard",
    safeForDemo: true,
    routeIndex: 26,
  },
];

export const preparedRoute: [number, number][] = [
  [-0.0196, 51.5384],
  [-0.0188, 51.5385],
  [-0.01795, 51.5389],
  [-0.0168, 51.5395],
  [-0.0156, 51.54],
  [-0.01485, 51.5404],
  [-0.0152, 51.5413],
  [-0.0168, 51.5421],
  [-0.0184, 51.5418],
  [-0.0194, 51.5409],
  [-0.0198, 51.5397],
  [-0.0196, 51.5384],
];

export const seededObservations = [
  {
    id: "OBS-001",
    category: "route obstruction",
    modality: "fused",
    source: "demo_import",
    privacyState: "redacted",
  },
  {
    id: "OBS-002",
    category: "signage",
    modality: "vision",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-003",
    category: "congestion",
    modality: "voice",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-004",
    category: "waste",
    modality: "vision",
    source: "demo_import",
    privacyState: "redacted",
  },
  {
    id: "OBS-005",
    category: "accessibility",
    modality: "fused",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-006",
    category: "crossing works",
    modality: "vision",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-007",
    category: "crowd flow",
    modality: "fused",
    source: "demo_import",
    privacyState: "redacted",
  },
  {
    id: "OBS-008",
    category: "cycle lane",
    modality: "vision",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-009",
    category: "lift status",
    modality: "voice",
    source: "demo_import",
    privacyState: "safe",
  },
  {
    id: "OBS-010",
    category: "surface damage",
    modality: "vision",
    source: "demo_import",
    privacyState: "safe",
  },
];
